server:
  port: 8087
spring:
  application:
    name: ureport

  datasource:
    #5版本用com.mysql.jdbc.Driver，6以上用com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    password: password123
    username: taoqy
    #本地测试用的：
    url: jdbc:mysql://127.0.0.1:3306/ureport?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#    url: jdbc:mysql://10.1.2.42:3306/db_sxzd?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#    password: qmjk
#    username: qmjk
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  instance:
    #代表本地别名，搭建eurekaserver集群的时候用到
    hostname: eureka_master
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #      如果不配会一直请求8761端口
      defaultZone: http://localhost:8081/eureka
  #eureka server刷新readCacheMap的时间，
  #注意，client读取的是readCacheMap，
  #这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
  #默认30s
  server:
    responseCacheUpdateInvervalMs: 3000
    #eureka server缓存readWriteCacheMap失效时间，
    #这个只有在这个时间过去后缓存才会失效，失效前不会更新，
    #过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
    #由于启用了evict其实就用不太上改这个配置了
    #默认180s
    responseCacheAutoExpirationInSeconds: 180
    #启用主动失效，并且每次主动失效检测间隔为5s
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    evictionIntervalTimerInMs: 5000
mybatis:
  type-aliases-package: com.digital.taoqy.entity
  configuration:
    map-underscore-to-camel-case: true